# Generated by Django 4.2.20 on 2025-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='https://cdn-icons-png.flaticon.com/512/8552/8552832.png', max_length=100, null=True),
        ),
    ]
